export const LOGIN_DELIVERY_PERSON_REQUEST = "LOGIN_DELIVERY_PERSON_REQUEST";
export const LOGIN_DELIVERY_PERSON_SUCCESS = "LOGIN_DELIVERY_PERSON_SUCCESS";
export const LOGIN_DELIVERY_PERSON_FAIL = "LOGIN_DELIVERY_PERSON_FAIL";